### ISSUE TITLE
Problem hash

### ISSUE THREAD

**Issue by Dr0gon23** [Yoruwu/pyrogramsessiongen#3]
When I start the process and enter the HASH, it gives me this error. How can I resolve it?

`Enter Phone number when asked.

Traceback (most recent call last):
  File "C:\Users\F\pyrogramsessiongen-main\pyrogramsessiongen-main\gen.py", line 50, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\F\pyrogramsessiongen-main\pyrogramsessiongen-main\gen.py", line 44, in main
    await i.start()
  File "C:\Users\Francesco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\F\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\F\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrogram\client.py", line 616, in load_session
    await self.storage.open()
  File "C:\Users\F\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyrogram\storage\file_storage.py", line 58, in open
    self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file`

**Comment by Dr0gon23** [comment]
Edit Okay, I think I've understood the issue. sqlite3.OperationalError occurs when there are multiple processes using the same session file. But how do I stop it if I've killed everything and reinstalled the Pyrogram library?

**Comment by Dr0gon23** [comment]
Okay, I think I've understood the issue. sqlite3.OperationalError occurs when there are multiple processes using the same session file. But how do I stop it if I've killed everything and reinstalled the Pyrogram library?

**Comment by Yoruwu** [comment]
@Dr0gon23 

The script creates a hidden memory file. U can see it by doing ls -al in the scripts directory.

Delete that, that should fix the same session problem.
If not check if asyncio works correctly on ur machine.

TBF I only tested the script on Linux and macOS, not on Windows 😅. I'll spin up a VM asap to try myself.

**Comment by Dr0gon23** [comment]
@Yoruwu 
Which script directory? Because in the Python directory, there's nothing, and I can't find any other script directories. When I first deployed it, it worked. I also used your SRCBotX repository in combination, but when I typed /start in the Telegram bot, it gave me different errors, so I wanted to redo the process, but now I'm encountering these issues.

 I've used the main SaveRestrictedContentBot repository by vasusen-code on a Linux VPS in the past, and it worked for a few months before it started giving problems. Now it's not working anymore, and I don't have access to a VPS to try again, so unfortunately, I have to try it locally.

**Comment by Yoruwu** [comment]
Alright I understand.

In the dir where u saved the script to. Like /Downloads/gen.py or /Desktop/gen.py :)

My SaveBot repo isn't working ATM, so best use the real deal :D
Good alternative is: 
https://github.com/anasty17/mirror-leech-telegram-bot

If the bot dies while typing /start, then some dependencys are missing.

**Comment by Dr0gon23** [comment]
I checked, and there are no hidden files. Thanku for the advice. I'm trying to take a look, and there's a lot of work to do... like using Google services. I don't like that the content gets uploaded to Google Drive, and I'd prefer the content to be extracted from restricted channels and then copied to the Telegram chat with the bot

**Comment by Yoruwu** [comment]
You don't have to use the drive feature. It's there but you don't have to use it :)

**Comment by Dr0gon23** [comment]
I'm trying to follow your advice. I've configured the config file and installed the requirements. I encountered some issues during the installation of the packages aria2 and qbittorrent, but since they are not necessary, I removed them. When I distribute the script, I get this error: 

_"File "\mirror-leech-telegram-bot-master\bot_init_.py", line 16, in <module> from uvloop import install ModuleNotFoundError: No module named 'uvloop'"_ 

And uvloop is already installed. The script has been distributed locally. Can you advise me on what to do?

**Comment by Dr0gon23** [comment]
Update: Okay, I've discovered that I can't install uvloop on Windows, and I need Linux for that. I tried to set up the software, but despite that, I have another issue. It says, "root - ERROR - BOT_TOKEN variable is missing! Exiting now," But the bot's token is entered correctly.🤕
